import { z } from 'zod';

/** Independent single-city powers. Each borrows an existing culture's art and unit roster; only name, colour, motto and lore are its own. */
export const cityStateSchema = z.object({
  id: z.string().regex(/^citystate\.[a-z_]+$/),
  name: z.string().min(1).max(40),
  cultureId: z.string().regex(/^faction\.[a-z_]+$/),
  color: z.number().int().min(0).max(0xffffff),
  motto: z.string().min(1).max(80),
  description: z.string().min(1).max(400),
}).strict();
export type CityStateDefinition = z.infer<typeof cityStateSchema>;

export const CITY_STATES: readonly CityStateDefinition[] = [
  { id: 'citystate.bellowstead', name: 'Bellowstead', cultureId: 'faction.ashen_compact', color: 0xd5aba5, motto: 'Every mark answers for its maker.', description: 'A one-city crafthold of kiln courts and bellows yards, governed by the masters whose marks are stamped on its work. Bellowstead swears no oath it cannot repair and accepts no charter that would make its workshops answer to a council it cannot walk to.' },
  { id: 'citystate.pyrefell', name: 'Pyrefell', cultureId: 'faction.cinder_march', color: 0xdfa086, motto: 'Dig where the fire finished.', description: 'A mining hold in the burnt fells, where crews cut ore from ground the Ashfall buried and the beacon line is lit each night out of habit. Pyrefell sells ore to any banner and lets none of them past its gate.' },
  { id: 'citystate.dunwell', name: 'Dunwell', cultureId: 'faction.cistern_assembly', color: 0xdccbb2, motto: 'Drink at the measure, not above it.', description: 'A caravan stop above three deep cisterns in the dry basins, where households and guests alike draw at a posted measure read aloud every morning. Dunwell has watered armies on both sides of a season’s fighting and refuses to say which it preferred.' },
  { id: 'citystate.candlerest', name: 'Candlerest', cultureId: 'faction.lantern_hospices', color: 0xddda92, motto: 'The door is open. The knife stays outside.', description: 'A walled hospice town at a road junction, keeping clean water, dry beds and a lit door for anyone who comes unarmed. Candlerest treats the wounded of every banner and has buried enough of them to stop asking whom they served.' },
  { id: 'citystate.grasshalt', name: 'Grasshalt', cultureId: 'faction.sable_steppe', color: 0x99a762, motto: 'Camp here. Do not settle here.', description: 'A permanent halt on the open grass where camp households meet to trade horses, hides and news, under a standing rule that no company may pitch inside the stone ring twice in a season. Grasshalt holds pasture it will not plough.' },
  { id: 'citystate.quickfallow', name: 'Quickfallow', cultureId: 'faction.emberwake_convocation', color: 0xbdcca4, motto: 'Ash is only soil that is late.', description: 'A resettlement town in the outer ash belts whose seed rooms hold varieties nobody else kept, planted out each year in test strips across the grey ground. Quickfallow gives seed to neighbours it cannot defend and keeps the account of who returned it.' },
  { id: 'citystate.sixways', name: 'Sixways', cultureId: 'faction.manytrack_moot', color: 0x9dbb8b, motto: 'Six roads in. No road owned.', description: 'Six old roads meet at a timber moot-ground where horned, furred and human households hear one another’s claims in the open and go home the same night. Sixways keeps no wall on the road side and has never agreed which of its gates is the front one.' },
  { id: 'citystate.spindlewood', name: 'Spindlewood', cultureId: 'faction.morrow_spore', color: 0xa0dd9d, motto: 'Shelter is not a debt.', description: 'A refuge grown into a town beneath the underwood canopy, settled by households that fled three different collapses and agreed not to question one another about the fourth. Spindlewood admits newcomers on a year of work and turns away nobody who arrives without a banner.' },
  { id: 'citystate.willowmere', name: 'Willowmere', cultureId: 'faction.mire_courts', color: 0x78ba7e, motto: 'The water decides. We only record it.', description: 'A fen town of stilt halls around a slow mere, still keeping the season-court forms its old landlords used and applying them to those landlords’ descendants. Willowmere hears every claim in flood season and enforces none until the water goes down.' },
  { id: 'citystate.loamferry', name: 'Loamferry', cultureId: 'faction.reedbound_council', color: 0xb4dac2, motto: 'Both banks pay the same.', description: 'A river town of ferry households that hold the only dependable crossing for forty miles and charge either bank the same, in coin, grain or work. Loamferry has cut its own cables twice rather than carry a column that would not say where it was going.' },
  { id: 'citystate.wrackpool', name: 'Wrackpool', cultureId: 'faction.brine_choir', color: 0x8dceb6, motto: 'Answer the shore that answers you.', description: 'A shelf settlement of brinefolk and shore households built around warm tidal pools that yield salt, shellfish and dye. Wrackpool answers proposals in open water-meeting, and has never answered one from a realm that arrived with its ships already anchored.' },
  { id: 'citystate.cullethaven', name: 'Cullethaven', cultureId: 'faction.glass_tide', color: 0x7eddd1, motto: 'We sell the wreck, not the story.', description: 'A free port on the glass coast whose yards buy Ashfall glass by weight and sell it cut, asking nothing about which beach it came off. Cullethaven honours a charter exactly as long as the charter is paid and keeps its harbour open to every flag at once.' },
  { id: 'citystate.bittern_quay', name: 'Bittern Quay', cultureId: 'faction.saltwind_remnant', color: 0xa3dee0, motto: 'Old debts drowned with old ships.', description: 'A salt port of evaporation pans and low tarred sheds, founded by crews who walked off wrecked charters and declared themselves clear of their owners’ books. Bittern Quay pledges a keel for one voyage at a time and will not sign for two.' },
  { id: 'citystate.hoarhold', name: 'Hoarhold', cultureId: 'faction.rimehorn_clans', color: 0x80bcdb, motto: 'Winter counts the guests.', description: 'A stone winter hold above the snowline keeping common stores for six clans, opened to travellers under a rule older than the Failing: shelter for anyone, for as long as the storm lasts, and no longer. Hoarhold has fed enemies through a blizzard and fought them at the thaw.' },
  { id: 'citystate.highseam', name: 'Highseam', cultureId: 'faction.iron_covenant', color: 0x6b84a8, motto: 'One gate. One price. No hurry.', description: 'A forge hold in a single high valley that closed its upper passes a century ago and trades finished ironwork through one gate on set days. Highseam quotes a price, holds it for a year, and has never explained how deep its workings run.' },
  { id: 'citystate.ninearch', name: 'Ninearch', cultureId: 'faction.wardhall_remnant', color: 0x6063a9, motto: 'Let the span be inspected.', description: 'A work-hall town built on and around a nine-arched bridge that its engineers inspect in public every spring. Ninearch will raise a road, a mole or a siege ramp for whoever pays the survey, and will not raise the same work twice for two sides of one war.' },
  { id: 'citystate.lodestair', name: 'Lodestair', cultureId: 'faction.velvet_meridian', color: 0xa39adf, motto: 'A measure is public or it is a rumour.', description: 'An observatory town on a dry upland stair, where the night’s readings are posted in the market by morning and any reader may challenge them. Lodestair sells copies to all comers and has twice refused, publicly, to sell a patron the exclusive use of a measurement.' },
  { id: 'citystate.hollowlease', name: 'Hollowlease', cultureId: 'faction.underhush_exchange', color: 0x8265a4, motto: 'Trade quietly or trade elsewhere.', description: 'A market town in the shallow galleries under a wooded escarpment, where every stall holds a lease with clauses on smoke, noise and repair. Hollowlease houses more residents than traders and evicts by vote when a tenant’s trade shakes the ceiling.' },
  { id: 'citystate.chalkvigil', name: 'Chalkvigil', cultureId: 'faction.sepulchral_synod', color: 0xd1aee0, motto: 'Count them all. Name them all.', description: 'A terrace city cut into chalk, whose ossuaries hold the named dead of a dozen towns that no longer exist and whose keepers read a portion of the roll aloud each day. Chalkvigil charges for burial, never for the reading, and releases no name to a claimant of inheritance.' },
  { id: 'citystate.endleaf', name: 'Endleaf', cultureId: 'faction.margin_observance', color: 0xbf8dc4, motto: 'Keep the blank page as well.', description: 'A small archive station at the edge of settled country, staffed in rotation, which copies what it is given and files the gaps as carefully as the text. Endleaf keeps sealed cases it will not open, and posts in the entry hall the exact number of them.' },
  { id: 'citystate.duskpress', name: 'Duskpress', cultureId: 'faction.vesper_court', color: 0xa465a2, motto: 'The vintage is owed. Nothing else is.', description: 'A vineyard town in a shuttered upland valley whose households bought out their old estate’s inherited provisions and now owe it wine and nothing further. Duskpress keeps the shutters in repair, keeps its patrons at the head of the valley, and keeps the bill of sale on public view.' },
  { id: 'citystate.windlass_ledge', name: 'Windlass Ledge', cultureId: 'faction.cairnwing_concord', color: 0xdd9dc3, motto: 'Nothing rises for free.', description: 'A lift-port on a red escarpment ledge where cairnfolk and human crews work the windlasses that raise every sack of grain and every dressed stone from the lower landings. Windlass Ledge sets its lift rate at open hearing and cuts its cables for nobody.' },
  { id: 'citystate.lockmouth', name: 'Lockmouth', cultureId: 'faction.red_sluice', color: 0xcb869a, motto: 'Whoever holds the gates owes the fields.', description: 'A canal town at the head of a lowland channel network, run by a board of gate-keepers elected by the households the water reaches. Lockmouth once opened its gates to drown an approaching column and has been arguing about the ruined fields ever since.' },
  { id: 'citystate.tollfast', name: 'Tollfast', cultureId: 'faction.unsealed_companies', color: 0xd26072, motto: 'Paid work ends. Debts should end too.', description: 'A company hold in a rebuilt toll fort on a ruined road corridor, where veterans hire out by the season and let every contract lapse at its term. Tollfast collects no toll, inherits no one’s oath, and keeps the only honest account of what the corridor’s fighting has cost.' },
];
