import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { expect, test } from '@playwright/test';
import { serializeGame } from '@theandril/sim';
import { exportSave } from '@theandril/persistence';
import { borderBattleCampaign } from '../../packages/test-fixtures/src/combat-fixture';
import { closeCampaignOptions, closeManagement, openCampaignJournal, openRealmAffairs, openSelectedOrders } from '../gameplay/ui-navigation';

test('built battlefield loads its exact approved battle page and preserves real manual abilities and saved outcomes without development hooks', async ({ page, baseURL }, info) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  const catalog = JSON.parse(await readFile(new URL('../../assets/art/runtime/catalog.json', import.meta.url), 'utf8')) as { atlases: { id: string; sha256: string }[] };
  const approved = catalog.atlases.find(atlas => atlas.id === 'battle')!;
  await page.goto('./');
  expect(await page.evaluate(() => typeof window.__THEANDRIL__)).toBe('undefined');
  await page.getByLabel('Import save file').setInputFiles({ name: 'production-battle.theandril', mimeType: 'application/gzip', buffer: Buffer.from(await exportSave(serializeGame(borderBattleCampaign()))) });
  await expect(page.getByTestId('feedback')).toContainText('Imported campaign');
  await openRealmAffairs(page);
  await page.getByRole('button', { name: 'Declare war on Reedbound Council', exact: true }).click();
  await openSelectedOrders(page);
  const battleUrl = new URL('art/battle.png', baseURL).href;
  const loaded = page.waitForResponse(response => response.url() === battleUrl);
  await page.getByRole('button', { name: 'Attack Reedbound Watch (army.4)', exact: true }).click();
  const image = await loaded; expect(image.ok()).toBe(true);
  expect(createHash('sha256').update(await image.body()).digest('hex')).toBe(approved.sha256);
  const battle = page.getByTestId('battle-panel');
  await expect(battle).toBeVisible();
  await expect(page.getByRole('checkbox', { name: /^Automatic Set shields/ })).toBeChecked();
  await page.getByRole('button', { name: /^Set shields \(/ }).click();
  await page.getByRole('combobox', { name: 'Inspect formation or officer', exact: true }).selectOption('formation.2');
  await expect(battle).toContainText('6 ward');
  await expect(page.getByTestId('battle-round')).toHaveText('0');
  await page.getByRole('button', { name: 'Step one battle round', exact: true }).click();
  await expect(page.getByTestId('battle-round')).toHaveText('1');
  await page.getByTestId('map-container').screenshot({ path: info.outputPath('production-battlefield.png') });
  const menu = page.getByTestId('campaign-menu');
  if (!await menu.evaluate(element => (element as HTMLDetailsElement).open)) await menu.locator('summary').click();
  await page.getByRole('button', { name: 'Save campaign', exact: true }).click();
  await expect(page.getByTestId('feedback')).toContainText('Campaign saved');
  await closeCampaignOptions(page);
  await page.getByRole('button', { name: 'Auto-resolve battle', exact: true }).click();
  await openCampaignJournal(page);
  await expect(page.getByTestId('battle-report')).toBeVisible();
  // Compare all account text, including the closed formation/round disclosure;
  // innerText instead applies CSS capitalization and omits that hidden account.
  const outcome = await page.getByTestId('battle-report').textContent();
  expect(outcome).toBeTruthy();
  await closeManagement(page);
  if (!await menu.evaluate(element => (element as HTMLDetailsElement).open)) await menu.locator('summary').click();
  await page.getByRole('button', { name: 'Load campaign', exact: true }).click();
  await expect(page.getByTestId('battle-round')).toHaveText('1');
  await closeCampaignOptions(page);
  await page.getByRole('button', { name: 'Auto-resolve battle', exact: true }).click();
  await openCampaignJournal(page);
  await expect(page.getByTestId('battle-report')).toHaveText(outcome!);
  expect(await page.evaluate(() => typeof window.__THEANDRIL__)).toBe('undefined');
  expect(errors).toEqual([]);
});
