import { expect, test } from '@playwright/test';
import { getObservation, serializeGame, stateHash } from '@theandril/sim';
import { campaignMenu, exportedTravel } from '../gameplay/group-movement-fixture';
import { closeManagement, openRegistry, openSelectedOrders, selectFromRegistry } from '../gameplay/ui-navigation';

test('generated production adopts a defensive theater through ordinary controls and restores its exact saved campaign without development hooks', async ({ page }, testInfo) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('./');
  await page.getByRole('textbox', { name: 'World seed', exact: true }).fill('20260927');
  await page.getByRole('combobox', { name: 'World size', exact: true }).selectOption('tiny');
  await page.getByRole('spinbutton', { name: 'Faction count', exact: true }).fill('2');
  await page.getByRole('spinbutton', { name: 'City-states', exact: true }).fill('0');
  await page.getByRole('button', { name: 'Begin campaign', exact: true }).click();
  await expect(page.getByTestId('feedback')).toContainText('Your people await a hearth.');
  await expect(page.getByRole('button', { name: 'End turn', exact: true })).toBeEnabled();
  expect(await page.evaluate(() => typeof window.__THEANDRIL__)).toBe('undefined');
  await selectFromRegistry(page, 'armies', /Hearth caravan/); await openSelectedOrders(page);
  await page.getByRole('textbox', { name: 'Settlement name', exact: true }).fill('Watch Hearth');
  await page.getByRole('button', { name: 'Found settlement', exact: true }).click();
  await openRegistry(page, 'armies');
  await page.getByRole('searchbox', { name: 'Search your realm' }).fill('');
  await page.getByRole('button', { name: 'Select matching armies', exact: true }).click();
  const panel = page.getByTestId('defense-theaters'); await panel.locator(':scope > summary').click();
  await panel.getByRole('textbox', { name: 'Theater name', exact: true }).fill('Home defense');
  await panel.getByRole('checkbox', { name: /^Watch Hearth · hex / }).check();
  await panel.getByRole('button', { name: 'Use checked armies (1)', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await panel.getByRole('button', { name: 'Create theater', exact: true }).focus(); await page.keyboard.press('Enter');
  await expect(page.getByTestId('theater-report')).toContainText('Home defense · Enabled');
  const created = await exportedTravel(page), owner = created.game.turnOwnerId;
  expect(created.game.theaters[0]).toMatchObject({ name: 'Home defense', enabled: true, lastRunTurn: null, lastDispatches: [] });
  expect(created.game.theaters[0]!.armyIds).toHaveLength(1);
  await page.getByTestId('campaign-menu').locator(':scope > summary').click();
  await page.getByRole('button', { name: 'End turn', exact: true }).click();
  await expect(page.getByTestId('turn-counter')).toHaveText('Turn 2'); await expect(page.getByRole('button', { name: 'End turn', exact: true })).toBeEnabled();
  const allocated = await exportedTravel(page), report = getObservation(allocated.game, owner).theaters![0]!;
  expect(report.lastRunTurn).toBe(2); expect(report.missingGuards).toBe(0);
  expect(report.hearths[0]!.stationed + report.hearths[0]!.incoming).toBe(1);
  await page.getByRole('button', { name: 'Save campaign', exact: true }).click(); await expect(page.getByTestId('feedback')).toContainText('Campaign saved.');
  await openRegistry(page, 'armies'); await panel.locator(':scope > summary').click();
  await panel.getByRole('combobox', { name: 'Defensive theater', exact: true }).selectOption(report.id);
  await panel.getByRole('button', { name: 'Pause theater', exact: true }).click();
  await expect(page.getByTestId('theater-report')).toContainText('Home defense · Paused');
  await page.reload(); await page.getByRole('button', { name: 'Load campaign', exact: true }).click(); await expect(page.getByTestId('feedback')).toContainText('Campaign restored.');
  const restored = await exportedTravel(page); expect(stateHash(restored.game)).toBe(stateHash(allocated.game)); expect(restored.archive).toEqual(allocated.archive);
  await page.reload(); await page.getByLabel('Import save file').setInputFiles({ name: 'generated-defense.theandril', mimeType: 'application/gzip', buffer: allocated.bytes });
  await expect(page.getByTestId('feedback')).toContainText('Imported campaign');
  const portable = await exportedTravel(page); expect(serializeGame(portable.game)).toBe(serializeGame(allocated.game)); expect(portable.archive).toEqual(allocated.archive);
  await openRegistry(page, 'armies'); await panel.locator(':scope > summary').focus(); await page.keyboard.press('Enter');
  await panel.getByRole('combobox', { name: 'Defensive theater', exact: true }).selectOption(report.id);
  await panel.getByRole('button', { name: 'Pause theater', exact: true }).scrollIntoViewIfNeeded();
  await page.evaluate(() => new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))));
  await page.screenshot({ path: testInfo.outputPath('production-defense-theater-restored-narrow.png') });
  await closeManagement(page); await campaignMenu(page);
  expect(await page.evaluate(() => typeof window.__THEANDRIL__)).toBe('undefined');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); expect(errors).toEqual([]);
});
