import { expect, test, type Page } from '@playwright/test';
import { parseRuntimeCatalog } from '@theandril/art-pipeline/runtime';
import { serializeGame } from '@theandril/sim';
import { exportSave } from '@theandril/persistence';
import { borderBattleCampaign } from '../../packages/test-fixtures/src/combat-fixture';

async function begin(page: Page): Promise<void> {
  await page.goto('/');
  await page.getByRole('textbox', { name: 'World seed', exact: true }).fill('20260905');
  await page.getByRole('combobox', { name: 'World size', exact: true }).selectOption('tiny');
  await page.getByRole('button', { name: 'Begin campaign', exact: true }).click();
  await expect(page.getByTestId('turn-counter')).toHaveText('Turn 1');
  await expect(page.getByTestId('map-container').locator('canvas')).toBeVisible();
}

test('approved native assets power the map while Art Lab inspects real animations, rectangles, palette and tile repetition without changing the campaign', async ({ page }, testInfo) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await begin(page);
  const response = await page.request.get('/art/catalog.json'); expect(response.ok()).toBe(true);
  const catalog = parseRuntimeCatalog(await response.json());
  const guard = catalog.assets.find(asset => asset.contentIds.includes('unit.guard'));
  const terrain = catalog.assets.find(asset => asset.contentIds.includes('terrain.grassland'));
  expect(guard).toBeTruthy(); expect(terrain).toBeTruthy();
  await expect.poll(() => page.evaluate(() => window.__THEANDRIL__?.getArtDiagnostics()?.state)).toBe('ready');
  await expect.poll(() => page.evaluate(() => window.__THEANDRIL__?.getArtDiagnostics()?.visibleSprites ?? 0)).toBeGreaterThan(0);
  await expect.poll(() => page.evaluate(() => window.__THEANDRIL__?.getArtDiagnostics()?.terrainSpriteCells ?? 0)).toBeGreaterThan(0);
  const original = await page.evaluate(() => window.__THEANDRIL__?.getStateHash());
  await page.getByRole('button', { name: 'Zoom in', exact: true }).click();
  const starterIds = ['unit.colonist.ashen_compact', 'unit.scout.ashen_compact'];
  await expect.poll(() => page.evaluate(() => window.__THEANDRIL__?.getArtDiagnostics()?.lod)).toBe('near-sprites');
  await expect.poll(() => page.evaluate(() => window.__THEANDRIL__?.getArtDiagnostics()?.visibleAssetIds)).toEqual(expect.arrayContaining(starterIds));
  for (const id of starterIds) expect(catalog.assets.find(asset => asset.id === id)?.frames).toHaveLength(1);
  expect(await page.evaluate(() => window.__THEANDRIL__?.getArtDiagnostics()?.visibleAnimationFrames)).toEqual([]);
  const renderedFrame = await page.evaluate(() => window.__THEANDRIL__?.getPerformanceCounters().frameCount ?? 0);
  await expect.poll(() => page.evaluate(() => window.__THEANDRIL__?.getPerformanceCounters().frameCount ?? 0)).toBeGreaterThan(renderedFrame + 15);
  expect(await page.evaluate(() => window.__THEANDRIL__?.getArtDiagnostics()?.visibleAnimationFrames)).toEqual([]);
  expect(await page.evaluate(() => window.__THEANDRIL__?.getStateHash())).toBe(original);
  await page.screenshot({ path: testInfo.outputPath('approved-sprites-near.png'), fullPage: true });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await expect.poll(() => page.evaluate(() => window.__THEANDRIL__?.getArtDiagnostics()?.visibleAnimationFrames.length)).toBe(0);
  expect(await page.evaluate(() => window.__THEANDRIL__?.getStateHash())).toBe(original);
  await page.getByRole('button', { name: 'Art Lab', exact: true }).click();
  const lab = page.getByRole('dialog', { name: 'Art Lab', exact: true });
  await expect(lab.getByTestId('art-catalog-validation')).toContainText('Manifest validated');
  await lab.getByLabel('Search art assets', { exact: true }).fill('unit.guard');
  await lab.getByRole('button', { name: `Inspect ${guard!.id}`, exact: true }).click();
  await expect(lab.getByTestId('art-consumer')).toContainText('Current gameplay consumer');
  await expect(lab.getByTestId('art-preview-canvas')).toBeVisible();
  await lab.getByRole('combobox', { name: 'Native zoom', exact: true }).selectOption('1');
  await expect(lab.getByTestId('art-preview-canvas')).toHaveAttribute('width', String(guard!.nativeResolution.width));
  await lab.getByRole('combobox', { name: 'Native zoom', exact: true }).selectOption('8');
  await expect(lab.getByTestId('art-preview-canvas')).toHaveAttribute('width', String(guard!.nativeResolution.width * 8));
  await lab.getByRole('combobox', { name: 'Alpha background', exact: true }).selectOption('light');
  await lab.getByLabel('Show alpha bounds', { exact: true }).uncheck();
  await lab.getByLabel('Show pivot', { exact: true }).uncheck();
  expect(guard!.frames.length).toBeGreaterThan(1);
  const firstGenericPixels = await lab.getByTestId('art-preview-canvas').evaluate(canvas => (canvas as HTMLCanvasElement).toDataURL());
  await lab.getByRole('button', { name: 'Next frame', exact: true }).click();
  await expect(lab.getByTestId('art-frame-counter')).toContainText('Frame 2 /');
  await expect.poll(() => lab.getByTestId('art-preview-canvas').evaluate(canvas => (canvas as HTMLCanvasElement).toDataURL())).not.toBe(firstGenericPixels);
  await lab.getByRole('button', { name: 'Play animation', exact: true }).click();
  await expect(lab.getByTestId('art-frame-counter')).not.toContainText('Frame 2 /');
  await lab.getByRole('button', { name: 'Pause animation', exact: true }).click();
  await lab.getByRole('combobox', { name: 'Native zoom', exact: true }).selectOption('4');
  await lab.screenshot({ path: testInfo.outputPath('art-lab-native-animation.png') });
  await lab.getByRole('tab', { name: 'Atlas rectangles', exact: true }).click();
  await expect(lab.getByTestId('art-atlas-canvas')).toBeVisible();
  await lab.screenshot({ path: testInfo.outputPath('art-lab-atlas-rectangles.png') });
  await lab.getByRole('tab', { name: 'Manifest & QA', exact: true }).click();
  await expect(lab.getByTestId('art-validation')).toContainText('Machine checks passed');
  await expect(lab.getByLabel('Asset manifest', { exact: true })).toContainText('sourceRefs');
  await lab.getByLabel('Search art assets', { exact: true }).fill('terrain.grassland');
  await lab.getByRole('button', { name: `Inspect ${terrain!.id}`, exact: true }).click();
  await lab.getByLabel('Tile repeat preview', { exact: true }).check();
  await lab.getByRole('combobox', { name: 'Native zoom', exact: true }).selectOption('2');
  await expect(lab.getByTestId('art-repeat-canvas')).toBeVisible();
  await lab.screenshot({ path: testInfo.outputPath('art-lab-terrain-repeat.png') });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect(await lab.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true);
  await lab.getByTestId('art-repeat-canvas').scrollIntoViewIfNeeded();
  await lab.screenshot({ path: testInfo.outputPath('art-lab-narrow.png') });
  await page.keyboard.press('Escape');
  await expect(lab).not.toBeVisible();
  await expect(page.getByRole('button', { name: 'Art Lab', exact: true })).toBeFocused();
  expect(await page.evaluate(() => window.__THEANDRIL__?.getStateHash())).toBe(original);
  await testInfo.attach('art-review-metadata.json', { body: JSON.stringify({ annotations: ['Approved faction sprites keep separate ownership shapes; selected range remains above art.', 'Faction starter poses are genuinely static; the retained generic guard demonstrates distinct frame pixels and real playback in Art Lab.', 'Native preview uses exact nearest integer zoom; the live regular hex grid uses explicitly disclosed fractional fit.', 'Tile-repeat view is native 56x64/48-row seam inspection, not generated geography.', 'Changing animation, zoom, reduced motion and inspecting assets preserved the initial canonical hash.'], catalogAssets: catalog.assets.length, diagnostics: await page.evaluate(() => window.__THEANDRIL__?.getArtDiagnostics()), metrics: await page.evaluate(() => window.__THEANDRIL__?.getPerformanceCounters()) }, null, 2), contentType: 'application/json' });
  expect(errors).toEqual([]);
});

test('actual guards, towns and far-zoom markers use observed entities rather than future-ready catalog content', async ({ page }, testInfo) => {
  const state = borderBattleCampaign();
  const town = Object.values(state.settlements).find(item => item.factionId === state.turnOwnerId)!;
  town.population = 12;
  await page.goto('/');
  await page.locator('input[type=file]').setInputFiles({ name: 'art-frontier.theandril', mimeType: 'application/gzip', buffer: Buffer.from(await exportSave(serializeGame(state))) });
  await expect(page.getByTestId('feedback')).toContainText('Imported campaign');
  await expect.poll(() => page.evaluate(() => window.__THEANDRIL__?.getArtDiagnostics()?.state)).toBe('ready');
  await expect.poll(() => page.evaluate(() => window.__THEANDRIL__?.getArtDiagnostics()?.visibleAssetIds ?? [])).toEqual(expect.arrayContaining(['unit.guard.ashen_compact', 'unit.guard.reedbound_council', 'settlement.city.ashen_compact']));
  const before = await page.evaluate(() => window.__THEANDRIL__?.getStateHash());
  await page.screenshot({ path: testInfo.outputPath('art-guard-city-frontier.png'), fullPage: true });
  for (let index = 0; index < 3; index++) await page.getByRole('button', { name: 'Zoom out', exact: true }).click();
  await expect.poll(() => page.evaluate(() => window.__THEANDRIL__?.getArtDiagnostics()?.lod)).toBe('strategic-glyphs');
  await expect.poll(() => page.evaluate(() => window.__THEANDRIL__?.getArtDiagnostics()?.visibleAssetIds ?? [])).toEqual(expect.arrayContaining(['ui.badge.ashen_compact', 'ui.badge.reedbound_council', 'ui.banner.ashen_compact']));
  const far = await page.evaluate(() => window.__THEANDRIL__?.getArtDiagnostics());
  expect(far?.visibleSprites).toBeGreaterThan(0);
  expect(far?.visibleAnimationFrames).toEqual([]);
  expect(far?.visibleEntityArt.every(entity => entity.presentation === 'strategic')).toBe(true);
  expect(await page.evaluate(() => window.__THEANDRIL__?.getStateHash())).toBe(before);
  await page.screenshot({ path: testInfo.outputPath('art-far-glyphs.png'), fullPage: true });
  await page.getByRole('button', { name: 'Art Lab', exact: true }).click();
  const lab = page.getByRole('dialog', { name: 'Art Lab', exact: true });
  await lab.getByLabel('Search art assets', { exact: true }).fill('unit.mage');
  await lab.getByRole('button', { name: 'Inspect unit.mage', exact: true }).click();
  await expect(lab.getByTestId('art-consumer')).toContainText('no current gameplay consumer');
});

test('a failed approved-art load is reported and retains playable procedural fallbacks', async ({ page }) => {
  await page.route('**/art/catalog.json', route => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ schemaVersion: 1, assets: [{ id: 'unit.guard', status: 'CANDIDATE' }] }) }));
  await begin(page);
  await expect(page.getByTestId('art-runtime-status')).toContainText('procedural fallback');
  expect(await page.evaluate(() => window.__THEANDRIL__?.getArtDiagnostics()?.warnings.length)).toBeGreaterThan(0);
  expect(await page.evaluate(() => window.__THEANDRIL__?.getArtDiagnostics()?.visibleSprites)).toBe(0);
  await page.getByLabel('Settlement name', { exact: true }).fill('Honest Hearth');
  await page.getByRole('button', { name: 'Found settlement', exact: true }).click();
  await expect(page.getByTestId('chronicle')).toContainText('Honest Hearth');
  await page.getByRole('button', { name: 'End turn', exact: true }).click();
  await expect(page.getByTestId('turn-counter')).toHaveText('Turn 2');
});

test('Art Lab refuses stale, mismatched and oversized atlas images before reporting pixel measurements', async ({ page }) => {
  await begin(page);
  await expect.poll(() => page.evaluate(() => window.__THEANDRIL__?.getArtDiagnostics()?.state)).toBe('ready');
  const before = await page.evaluate(() => window.__THEANDRIL__?.getStateHash());
  const catalog = parseRuntimeCatalog(await (await page.request.get('/art/catalog.json')).json());
  const atlas = catalog.atlases.find(item => item.id === catalog.assets.find(asset => asset.id === 'unit.guard')!.atlasId)!;
  const original = await (await page.request.get(atlas.imageUrl)).body();
  const pattern = `**${atlas.imageUrl}`;
  const corrupted = Buffer.from(original); corrupted[corrupted.length - 1] = corrupted[corrupted.length - 1]! ^ 1;
  await page.route(pattern, route => route.fulfill({ status: 200, contentType: 'image/png', body: corrupted }));
  await page.getByRole('button', { name: 'Art Lab', exact: true }).click();
  const lab = page.getByRole('dialog', { name: 'Art Lab', exact: true });
  await lab.getByLabel('Search art assets', { exact: true }).fill('unit.guard');
  await lab.getByRole('button', { name: 'Inspect unit.guard', exact: true }).click();
  await expect(lab.getByRole('alert')).toContainText('Atlas image hash mismatch');
  await expect(lab.getByTestId('art-preview-canvas')).toHaveCount(0);
  await expect(lab.getByTestId('art-pixel-metrics')).toHaveCount(0);
  await page.unroute(pattern);
  const mismatched = Buffer.from(original); mismatched.writeUInt32BE(atlas.width - 1, 16);
  await page.route(pattern, route => route.fulfill({ status: 200, contentType: 'image/png', body: mismatched }));
  await lab.getByRole('button', { name: 'Reload art catalog', exact: true }).click();
  await expect(lab.getByRole('alert')).toContainText('Atlas image dimensions mismatch');
  await expect(lab.getByTestId('art-pixel-metrics')).toHaveCount(0);
  await page.unroute(pattern);
  const oversized = Buffer.from(original); oversized.writeUInt32BE(8192, 16);
  await page.route(pattern, route => route.fulfill({ status: 200, contentType: 'image/png', body: oversized }));
  await lab.getByRole('button', { name: 'Reload art catalog', exact: true }).click();
  await expect(lab.getByRole('alert')).toContainText('4,096-pixel edge limit');
  await expect(lab.getByTestId('art-pixel-metrics')).toHaveCount(0);
  await expect(lab.getByTestId('art-preview-canvas')).toHaveCount(0);
  expect(await page.evaluate(() => window.__THEANDRIL__?.getStateHash())).toBe(before);
  expect(await page.evaluate(() => window.__THEANDRIL__?.getArtDiagnostics()?.state)).toBe('ready');
});
