import { expect, test } from '@playwright/test';
import { writeFile } from 'node:fs/promises';
import { serializeGame } from '@theandril/sim';
import { exportSave } from '@theandril/persistence';
import { borderBattleCampaign } from '../../packages/test-fixtures/src/combat-fixture';
import { openRealmAffairs, openSelectedOrders } from './ui-navigation';

test('390px battle inspection enlarges real soldiers, pans within the field and preserves paused orders and picks', async ({ page }, info) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  await page.getByLabel('Import save file').setInputFiles({ name: 'battle-inspection.theandril', mimeType: 'application/gzip', buffer: Buffer.from(await exportSave(serializeGame(borderBattleCampaign()))) });
  await expect(page.getByTestId('feedback')).toContainText('Imported campaign');
  await openRealmAffairs(page); await page.getByRole('button', { name: 'Declare war on Reedbound Council', exact: true }).click();
  await openSelectedOrders(page); await page.getByRole('button', { name: 'Attack Reedbound Watch (army.4)', exact: true }).click();
  await expect.poll(() => page.evaluate(() => window.__THEANDRIL__!.getArtDiagnostics()?.atlasPages)).toBe(5);
  await page.getByRole('combobox', { name: 'Playback speed', exact: true }).selectOption('0.5');
  await page.getByRole('button', { name: 'Brace', exact: true }).click();
  await page.getByRole('button', { name: 'Pause actions', exact: true }).click();
  const fit = await page.evaluate(() => ({ hash: window.__THEANDRIL__!.getStateHash(), scene: window.__THEANDRIL__!.getBattleDiagnostics()! }));
  expect(fit.scene.paused).toBe(true); expect(fit.scene.camera.zoom).toBe(1);
  const formationId = fit.scene.formations.find(item => item.side === 'attacker')!.id;
  await page.getByRole('combobox', { name: 'Inspect formation or officer', exact: true }).selectOption(formationId);
  await page.getByRole('button', { name: 'Focus selected', exact: true }).click();
  await expect.poll(() => page.evaluate(() => window.__THEANDRIL__!.getBattleDiagnostics()?.camera.zoom)).toBe(3);
  const detail = page.getByRole('combobox', { name: 'Battle view', exact: true });
  await detail.selectOption('4');
  await expect.poll(() => page.evaluate(() => window.__THEANDRIL__!.getBattleDiagnostics()?.camera.zoom)).toBe(4);
  const focused = await page.evaluate(() => window.__THEANDRIL__!.getBattleDiagnostics()!);
  expect(focused.selectedId).toBe(formationId); expect(focused.elapsedMs).toBe(fit.scene.elapsedMs);
  expect(focused.soldiers.map(soldier => [soldier.id, soldier.frameId, soldier.alive])).toEqual(fit.scene.soldiers.map(soldier => [soldier.id, soldier.frameId, soldier.alive]));
  expect(focused.height).toBeLessThanOrEqual(640);
  await page.getByTestId('map-container').screenshot({ path: info.outputPath('soldiers-focused-4x-390.png') });
  await page.screenshot({ path: info.outputPath('battle-inspection-controls-390.png') });
  await page.getByRole('button', { name: 'Pan battlefield left', exact: true }).click();
  const panned = await page.evaluate(() => window.__THEANDRIL__!.getBattleDiagnostics()!);
  expect(panned.camera.x).toBeGreaterThanOrEqual(focused.camera.x);
  expect(panned.camera.x).toBeGreaterThanOrEqual(panned.width - panned.width * 4); expect(panned.camera.x).toBeLessThanOrEqual(0);
  await page.getByRole('button', { name: 'Focus selected', exact: true }).click();
  await page.getByRole('combobox', { name: 'Inspect formation or officer', exact: true }).selectOption('');
  await expect.poll(() => page.evaluate(() => window.__THEANDRIL__!.getBattleDiagnostics()?.selectedId)).toBeNull();
  await page.getByTestId('map-container').scrollIntoViewIfNeeded();
  const pick = await page.evaluate(formationId => {
    const scene = window.__THEANDRIL__!.getBattleDiagnostics()!, field = document.querySelector('[data-testid=map-container]')!.getBoundingClientRect();
    const soldier = scene.soldiers.find(soldier => soldier.formationId === formationId && soldier.alive && scene.camera.x + soldier.x * scene.camera.zoom > 30 && scene.camera.x + soldier.x * scene.camera.zoom < scene.width - 30 && scene.camera.y + (soldier.y - 20 * soldier.scale) * scene.camera.zoom > 130 && scene.camera.y + (soldier.y - 20 * soldier.scale) * scene.camera.zoom < scene.height - 30)!;
    if (!soldier) throw new Error('Focused formation has no visible actual soldier to pick.');
    return { x: field.left + scene.camera.x + soldier.x * scene.camera.zoom, y: field.top + scene.camera.y + (soldier.y - 20 * soldier.scale) * scene.camera.zoom, formationId: soldier.formationId };
  }, formationId);
  await page.mouse.click(pick.x, pick.y);
  await expect.poll(() => page.evaluate(() => window.__THEANDRIL__!.getBattleDiagnostics()?.selectedId)).toBe(pick.formationId);
  await detail.selectOption('2');
  await expect.poll(() => page.evaluate(() => window.__THEANDRIL__!.getBattleDiagnostics()?.camera.zoom)).toBe(2);
  await detail.selectOption('1');
  await expect.poll(() => page.evaluate(() => window.__THEANDRIL__!.getBattleDiagnostics()?.camera)).toMatchObject({ zoom: 1, x: 0, y: 0 });
  const restored = await page.evaluate(() => ({ hash: window.__THEANDRIL__!.getStateHash(), scene: window.__THEANDRIL__!.getBattleDiagnostics()! }));
  expect(restored.hash).toBe(fit.hash); expect(restored.scene.paused).toBe(true); expect(restored.scene.elapsedMs).toBe(fit.scene.elapsedMs);
  expect(restored.scene.selectedId).toBe(formationId);
  expect(restored.scene.soldiers.map(soldier => [soldier.id, soldier.frameId, soldier.alive])).toEqual(fit.scene.soldiers.map(soldier => [soldier.id, soldier.frameId, soldier.alive]));
  await page.getByTestId('map-container').screenshot({ path: info.outputPath('soldiers-fit-restored-390.png') });
  await writeFile(info.outputPath('battle-camera.json'), JSON.stringify({ scope: 'Real war, attack and Brace command, paused before inspection. Actual4x sprite transform, bounded pan and pointer inverse; no canonical mutations or extra sprites.', fit, focused, panned, pick, restored }, null, 2));
});
