import { expect, test } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { serializeGame, stateHash } from '@theandril/sim';
import { exportSave } from '@theandril/persistence';
import { replayArchive, type ArchiveRecord, type ArchiveRulesVersion } from '@theandril/chronicle';
import { prosperityCampaign } from '../../packages/test-fixtures/src/victory-fixture';

test('AI watch plays a whole generated campaign, survives a save, and binds both complete chronicles at victory', async ({ page }, testInfo) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await page.getByLabel('World seed').fill('20260905');
  await page.getByLabel('World size').selectOption('tiny');
  await page.getByLabel('Campaign pace').selectOption('short');
  await page.getByLabel('Campaign mode').selectOption('watch');
  await page.getByRole('button', { name: 'Begin campaign', exact: true }).click();
  await expect(page.getByTestId('watch-controls')).toContainText('AI watch paused');
  await expect(page.getByRole('button', { name: 'End turn', exact: true })).toBeDisabled();
  await expect(page.getByRole('button', { name: 'Campaign chronicles', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: 'Step one round', exact: true }).click();
  await expect(page.getByTestId('turn-counter')).toHaveText('Turn 2');
  await expect(page.getByTestId('watch-controls')).toContainText('AI watch paused');
  const earlyHash = await page.evaluate(() => window.__THEANDRIL__?.getStateHash());
  await page.getByText('Campaign & settings', { exact: true }).click();
  await page.getByRole('button', { name: 'Save campaign', exact: true }).click();
  await expect(page.getByTestId('feedback')).toContainText('Campaign saved');
  await page.reload();
  await page.getByRole('button', { name: 'Load campaign', exact: true }).click();
  await expect(page.getByTestId('watch-controls')).toContainText('AI watch paused');
  expect(await page.evaluate(() => window.__THEANDRIL__?.getStateHash())).toBe(earlyHash);
  const started = Date.now();
  await page.getByRole('button', { name: 'Resume AI watch', exact: true }).click();
  // Real worker rounds with a 250ms UI yield between rounds; current mixed-army AI is active.
  const dialog = page.getByRole('dialog', { name: 'Campaign chronicles', exact: true });
  await expect(dialog).toBeVisible({ timeout: 25000 });
  const watchMs = Date.now() - started;
  await expect(dialog).toContainText('Complete record: generated start on turn 1');
  await expect(page.getByTestId('victory-result')).toContainText('achieved Prosperity');
  const finalHash = await page.evaluate(() => window.__THEANDRIL__?.getStateHash());
  const victory = await page.evaluate(() => window.__THEANDRIL__?.getSummary()?.victory);
  expect(victory?.turn).toBe(43); // Current rules; the original v4 turn46 seal has a separate frozen replay test.
  await dialog.getByLabel('History chapter', { exact: true }).selectOption('1');
  await expect(page.getByTestId('history-chapter')).toContainText('was founded');
  await page.screenshot({ path: testInfo.outputPath('history-tome.png'), fullPage: true });
  const historyDownload = page.waitForEvent('download');
  await dialog.getByRole('button', { name: 'Download history text', exact: true }).click();
  const historyPath = await (await historyDownload).path();
  if (!historyPath) throw new Error('History download missing');
  const history = await readFile(historyPath, 'utf8');
  expect(history).toContain('Turn 1 — New hearths');
  expect(history).toContain(`Turn ${victory!.turn} — The closing of the book`);
  expect(history).toContain('achieved Prosperity');
  await dialog.getByRole('tab', { name: 'History tome', exact: true }).focus();
  await page.keyboard.press('ArrowRight');
  await expect(dialog.getByRole('tab', { name: 'Technical log', exact: true })).toHaveAttribute('aria-selected', 'true');
  await expect(dialog.getByLabel('Technical log preview', { exact: true })).toContainText('Order 1');
  await dialog.getByLabel('Technical turn', { exact: true }).selectOption(String(victory!.turn - 1));
  await expect(dialog.getByLabel('Technical log preview', { exact: true })).toContainText('campaign_victory');
  const technicalDownload = page.waitForEvent('download');
  await dialog.getByRole('button', { name: 'Download technical JSON', exact: true }).click();
  const technicalPath = await (await technicalDownload).path();
  if (!technicalPath) throw new Error('Technical download missing');
  const technical = JSON.parse(await readFile(technicalPath, 'utf8')) as { initialSnapshot: unknown; initialHash: string; initialSaveVersion: ArchiveRulesVersion; records: ArchiveRecord[]; finalHash: string; finalHashVersion: ArchiveRulesVersion; victory: unknown };
  expect(technical.finalHash).toBe(finalHash);
  expect(technical.victory).toEqual(victory);
  expect(technical.records[0]?.turn).toBe(1);
  expect(technical.records.filter(record => !record.ok)).toHaveLength(0);
  expect(technical.records.flatMap(record => record.events).length).toBeGreaterThan(200);
  const replayed = replayArchive({ version: 2, mode: 'watch', coverage: 'complete', initialSave: JSON.stringify(technical.initialSnapshot), initialHash: technical.initialHash, initialSaveVersion: technical.initialSaveVersion, initialTurn: 1, records: technical.records, finalHash: technical.finalHash, finalHashVersion: technical.finalHashVersion });
  expect(stateHash(replayed)).toBe(finalHash);
  await page.screenshot({ path: testInfo.outputPath('technical-ledger.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await dialog.getByRole('tab', { name: 'History tome', exact: true }).click();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect(await dialog.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true);
  await dialog.screenshot({ path: testInfo.outputPath('history-narrow.png') });
  await page.keyboard.press('Escape');
  await expect(dialog).not.toBeVisible();
  await expect(page.getByRole('button', { name: 'Step one round', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Campaign chronicles', exact: true }).click();
  await expect(dialog).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('button', { name: 'Campaign chronicles', exact: true })).toBeFocused();
  await testInfo.attach('watch-performance.json', { body: JSON.stringify({ generatedStartToVictoryAfterReloadMs: watchMs, turn: victory?.turn, orders: technical.records.length, finalHash }, null, 2), contentType: 'application/json' });
  expect(errors).toEqual([]);
});

test('a human researches, adopts distinct policies, starts a public project and reads an honestly partial imported history', async ({ page }, testInfo) => {
  const prepared = prosperityCampaign();
  await page.goto('/');
  await page.locator('input[type=file]').setInputFiles({ name: 'prepared-hearths.theandril', mimeType: 'application/gzip', buffer: Buffer.from(await exportSave(serializeGame(prepared))) });
  await expect(page.getByTestId('feedback')).toContainText('Imported campaign');
  await page.getByRole('button', { name: 'Realm progression', exact: true }).click();
  const progression = page.getByRole('dialog', { name: 'Realm progression', exact: true });
  await progression.getByRole('button', { name: 'Research Civic accounts', exact: true }).click();
  await expect(progression.getByRole('button', { name: 'Research Civic accounts', exact: true })).toBeDisabled();
  await progression.getByRole('tab', { name: 'Institutions', exact: true }).click();
  await progression.getByRole('button', { name: 'Adopt Common stewardship', exact: true }).click();
  await expect(progression.getByRole('button', { name: 'Adopt Charter compact', exact: true })).toBeDisabled();
  await progression.getByRole('tab', { name: 'Military doctrine', exact: true }).click();
  await progression.getByRole('button', { name: 'Adopt March columns', exact: true }).click();
  await expect(progression.getByRole('button', { name: 'Adopt Shield cohesion', exact: true })).toBeDisabled();
  await progression.getByRole('tab', { name: 'Prosperity', exact: true }).click();
  await progression.getByLabel('Project settlement').selectOption('settlement.5');
  await progression.getByRole('button', { name: 'Start Hearth Exchange', exact: true }).click();
  await expect(progression.getByTestId('public-projects')).toContainText('active · 0/5');
  await progression.screenshot({ path: testInfo.outputPath('prosperity-project.png') });
  await page.keyboard.press('Escape');
  for (let offset = 1; offset <= 5; offset++) {
    await page.getByRole('button', { name: 'End turn', exact: true }).click();
    await expect(page.getByTestId('turn-counter')).toHaveText(`Turn ${prepared.turn + offset}`);
  }
  const chronicles = page.getByRole('dialog', { name: 'Campaign chronicles', exact: true });
  await expect(chronicles).toBeVisible();
  await expect(chronicles).toContainText(`Partial record: this campaign was imported on turn ${prepared.turn}`);
  await expect(page.getByTestId('victory-result')).toContainText('Ashen Compact achieved Prosperity');
  expect(await page.evaluate(() => window.__THEANDRIL__?.getSummary()?.progression)).toMatchObject({ technologies: ['technology.civic_accounts'], institutionId: 'institution.common_stewardship', doctrineId: 'doctrine.march_columns' });
});
