import { expect, test } from '@playwright/test';
import { createGame, serializeGame } from '@theandril/sim';
import { exportSave } from '@theandril/persistence';
import { cellTransferBytes, packCells } from '../../apps/web/src/cell-transfer';
import { empireLandCampaign } from '../../packages/test-fixtures/src/empire-land-fixture';
import { closeManagement, openRegistry, openSelectedOrders, selectFromRegistry } from './ui-navigation';

test('a hundred armies receive one group posting, retain individual overrides and restore through a real save', async ({ page }, testInfo) => {
  const game = empireLandCampaign('legendary');
  const own = Object.values(game.armies).filter(army => army.factionId === game.turnOwnerId).sort((a, b) => a.id < b.id ? -1 : 1);
  own.forEach((army, index) => { army.name = `Registry company ${String(index + 1).padStart(3, '0')}`; });
  expect(own).toHaveLength(100);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await page.locator('input[type=file]').setInputFiles({ name: 'group-postings.theandril', mimeType: 'application/gzip', buffer: Buffer.from(await exportSave(serializeGame(game))) });
  await expect(page.getByTestId('feedback')).toContainText('Imported campaign');
  const before = await page.evaluate(() => ({ hash: window.__THEANDRIL__!.getStateHash(), metrics: window.__THEANDRIL__!.getPerformanceCounters(), explored: window.__THEANDRIL__!.getSummary()!.exploredCells }));
  await openRegistry(page, 'armies');
  const registry = page.getByTestId('army-registry'), group = page.getByTestId('group-postings');
  await expect(registry.getByRole('button')).toHaveCount(25);
  await registry.getByRole('checkbox').first().focus(); await page.keyboard.press('Space');
  await page.getByRole('button', { name: 'Next registry page', exact: true }).click();
  await registry.getByRole('checkbox').first().check();
  const search = page.getByRole('searchbox', { name: 'Search your realm' });
  await search.fill('Registry company 100');
  await expect(group).toContainText('2 armies selected · 2 outside this filter');
  await group.getByRole('button', { name: 'Select matching armies', exact: true }).click();
  await expect(group).toContainText('3 armies selected · 2 outside this filter');
  await search.fill('');
  await group.getByRole('button', { name: 'Select matching armies', exact: true }).click();
  await expect(group).toContainText('100 armies selected');
  expect(await page.evaluate(() => window.__THEANDRIL__!.getStateHash())).toBe(before.hash);
  expect(await page.evaluate(() => window.__THEANDRIL__!.getPerformanceCounters().totalTransferBytes)).toBe(before.metrics.totalTransferBytes);
  await group.getByRole('button', { name: 'Post selected armies (100)', exact: true }).click();
  await expect(page.getByTestId('group-posting-results')).toContainText('100 orders accepted · 0 refused');
  await expect(group).toContainText('0 armies selected');
  const after = await page.evaluate(() => ({ view: window.__THEANDRIL__!.getSummary()!, hash: window.__THEANDRIL__!.getStateHash(), metrics: window.__THEANDRIL__!.getPerformanceCounters() }));
  expect(after.view.postings).toHaveLength(100);
  expect(after.view.postings.every(posting => posting.mode === 'hold' && posting.arrived)).toBe(true);
  expect(after.view.exploredCells).toBe(before.explored);
  expect(after.metrics.cellTransferBytes).toBe(cellTransferBytes(packCells([])));
  expect(after.metrics.totalTransferBytes - before.metrics.totalTransferBytes).toBe(after.metrics.transferBytes);
  await testInfo.attach('group-transfer.json', { body: JSON.stringify({ authored: 'Legendary, 40 owned hearths, 100 owned armies, 4000 total armies', commandMs: after.metrics.commandMs, transferBytes: after.metrics.transferBytes, cellTransferBytes: after.metrics.cellTransferBytes, publishedStates: 1, beforeHash: before.hash, afterHash: after.hash }, null, 2), contentType: 'application/json' });
  await page.screenshot({ path: testInfo.outputPath('group-postings-desktop.png') });
  await closeManagement(page);
  await page.getByTestId('campaign-menu').locator(':scope > summary').click();
  await page.getByRole('button', { name: 'Save campaign', exact: true }).click();
  await expect(page.getByTestId('feedback')).toContainText('Campaign saved.');
  await selectFromRegistry(page, 'armies', own[0]!.name);
  await openSelectedOrders(page);
  const posting = page.getByTestId('army-posting');
  await posting.locator(':scope > summary').click();
  await posting.getByLabel('On arrival').selectOption('join');
  await posting.getByRole('button', { name: 'Update posting', exact: true }).click();
  await expect.poll(() => page.evaluate(() => window.__THEANDRIL__!.getSummary()!.postings.filter(item => item.mode === 'join').length)).toBe(1);
  expect(await page.evaluate(() => window.__THEANDRIL__!.getSummary()!.postings.filter(item => item.mode === 'hold').length)).toBe(99);
  await page.setViewportSize({ width: 390, height: 844 });
  await openRegistry(page, 'armies');
  await search.fill('');
  await group.getByRole('button', { name: 'Select matching armies', exact: true }).click();
  await expect(group).toContainText('100 armies selected');
  await group.scrollIntoViewIfNeeded();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('group-postings-narrow.png') });
  await group.getByRole('button', { name: 'Clear selected postings (100)', exact: true }).click();
  await expect.poll(() => page.evaluate(() => window.__THEANDRIL__!.getSummary()!.postings.length)).toBe(0);
  await expect(page.getByTestId('group-posting-results')).toContainText('100 orders accepted · 0 refused');
  await closeManagement(page);
  await page.getByTestId('campaign-menu').locator(':scope > summary').click();
  await page.getByRole('button', { name: 'Load campaign', exact: true }).click();
  await expect(page.getByTestId('feedback')).toContainText('Campaign restored.');
  expect(await page.evaluate(() => window.__THEANDRIL__!.getStateHash())).toBe(after.hash);
  await openRegistry(page, 'armies');
  await expect(group).toContainText('0 armies selected');
  expect(errors).toEqual([]);
});

test('a partly refused group reports the canonical limit and retains only refused armies', async ({ page }) => {
  const game = createGame({ seed: 17, size: 'tiny', factionCount: 2 });
  const army = game.armies['army.1']!;
  // Authored boundary fixture: old lost-army postings are valid until the next
  // turn prunes them. Foreign records occupy the limit without exposing them.
  game.postings = [{ armyId: army.id, factionId: army.factionId, cell: army.cell, mode: 'hold' },
    ...Array.from({ length: 8191 }, (_, index) => ({ armyId: `army.expired.${String(index).padStart(4, '0')}`, factionId: game.factions[1]!.id, cell: game.world.starts[1]!, mode: 'hold' as const }))];
  await page.goto('/');
  await page.locator('input[type=file]').setInputFiles({ name: 'limited-group-postings.theandril', mimeType: 'application/gzip', buffer: Buffer.from(await exportSave(serializeGame(game))) });
  await expect(page.getByTestId('feedback')).toContainText('Imported campaign');
  await openRegistry(page, 'armies');
  const group = page.getByTestId('group-postings');
  await group.getByRole('button', { name: 'Select matching armies', exact: true }).click();
  await group.getByRole('button', { name: /^Post selected armies/ }).click();
  await expect(page.getByTestId('group-posting-results')).toContainText('1 orders accepted · 1 refused');
  await expect(page.getByTestId('group-posting-results')).toContainText('as many postings as it may');
  await expect(group).toContainText('1 armies selected');
  await expect(page.getByTestId('group-posting-results')).toContainText('Refused armies remain selected for review');
  await expect(group.getByRole('button', { name: /^Post selected armies/ })).toBeEnabled();
  expect(await page.evaluate(() => window.__THEANDRIL__!.getSummary()!.postings.length)).toBe(1);
});
