import { expect, test } from '@playwright/test';
import { applyCommand, serializeGame } from '@theandril/sim';
import { exportSave } from '@theandril/persistence';
import { cellTransferBytes, packCells } from '../../apps/web/src/cell-transfer';
import { empireLandCampaign } from '../../packages/test-fixtures/src/empire-land-fixture';
import { closeManagement, openRegistry, openSelectedOrders, selectFromRegistry } from './ui-navigation';

test('forty hearths receive shared charters across pages, preserve queues, and restore individual overrides', async ({ page }, testInfo) => {
  const game = empireLandCampaign('legendary');
  const towns = Object.values(game.settlements).filter(town => town.factionId === game.turnOwnerId).sort((a, b) => a.id < b.id ? -1 : 1);
  towns.forEach((town, index) => { town.name = `Registry hearth ${String(index + 1).padStart(3, '0')}`; });
  expect(towns).toHaveLength(40);
  expect(Object.values(game.armies).filter(army => army.factionId === game.turnOwnerId)).toHaveLength(100);
  expect(applyCommand(game, { type: 'queue', factionId: game.turnOwnerId, settlementId: towns[0]!.id, itemId: 'building.granary' }).ok).toBe(true);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await page.locator('input[type=file]').setInputFiles({ name: 'group-charters.theandril', mimeType: 'application/gzip', buffer: Buffer.from(await exportSave(serializeGame(game))) });
  await expect(page.getByTestId('feedback')).toContainText('Imported campaign');
  const before = await page.evaluate(() => ({ hash: window.__THEANDRIL__!.getStateHash(), view: window.__THEANDRIL__!.getSummary()!, metrics: window.__THEANDRIL__!.getPerformanceCounters() }));
  await openRegistry(page, 'settlements');
  const registry = page.getByTestId('settlement-registry'), group = page.getByTestId('group-charters');
  await expect(registry.getByRole('button')).toHaveCount(25);
  await registry.getByRole('checkbox').first().focus(); await page.keyboard.press('Space');
  await page.getByRole('button', { name: 'Next registry page', exact: true }).click();
  await registry.getByRole('checkbox').first().check();
  const search = page.getByRole('searchbox', { name: 'Search your realm' });
  await search.fill('Registry hearth 040');
  await expect(group).toContainText('2 hearths selected · 2 outside this filter');
  await group.getByRole('button', { name: 'Select matching hearths', exact: true }).click();
  await expect(group).toContainText('3 hearths selected · 2 outside this filter');
  await openRegistry(page, 'armies');
  await search.fill('');
  await page.getByTestId('army-registry').getByRole('checkbox').first().check();
  await openRegistry(page, 'settlements');
  await expect(group).toContainText('3 hearths selected');
  await group.getByRole('button', { name: 'Select matching hearths', exact: true }).click();
  await group.getByLabel('Charter focus').selectOption('wealth');
  await group.getByLabel('Coin ceiling per hearth').fill('24');
  await expect(group).toContainText('40 coin');
  expect(await page.evaluate(() => window.__THEANDRIL__!.getStateHash())).toBe(before.hash);
  expect(await page.evaluate(() => window.__THEANDRIL__!.getPerformanceCounters().totalTransferBytes)).toBe(before.metrics.totalTransferBytes);
  await page.screenshot({ path: testInfo.outputPath('group-charters-desktop.png') });
  await group.getByRole('button', { name: 'Apply charters (40)', exact: true }).click();
  await expect(page.getByTestId('group-charter-results')).toContainText('40 orders accepted · 0 refused');
  await expect(group).toContainText('0 hearths selected');
  const after = await page.evaluate(() => ({ view: window.__THEANDRIL__!.getSummary()!, hash: window.__THEANDRIL__!.getStateHash(), metrics: window.__THEANDRIL__!.getPerformanceCounters() }));
  expect(after.view.charters).toHaveLength(40);
  expect(after.view.charters.every(charter => charter.focus === 'wealth' && charter.ceiling === 24)).toBe(true);
  expect(after.view.ownSettlements.map(town => town.queue)).toEqual(before.view.ownSettlements.map(town => town.queue));
  expect(after.view.treasury).toBe(before.view.treasury);
  expect(after.view.exploredCells).toBe(before.view.exploredCells);
  expect(after.metrics.cellTransferBytes).toBe(cellTransferBytes(packCells([])));
  expect(after.metrics.totalTransferBytes - before.metrics.totalTransferBytes).toBe(after.metrics.transferBytes);
  await testInfo.attach('group-charter-transfer.json', { body: JSON.stringify({ authored: 'Legendary, 40 owned hearths, 100 owned armies, 4000 total armies; paid manual queue', commandMs: after.metrics.commandMs, transferBytes: after.metrics.transferBytes, cellTransferBytes: after.metrics.cellTransferBytes, publishedStates: 1, beforeHash: before.hash, afterHash: after.hash }, null, 2), contentType: 'application/json' });
  await openRegistry(page, 'armies');
  await expect(page.getByTestId('group-postings')).toContainText('1 armies selected');
  await closeManagement(page);
  await page.getByTestId('campaign-menu').locator(':scope > summary').click();
  await page.getByRole('button', { name: 'Save campaign', exact: true }).click();
  await expect(page.getByTestId('feedback')).toContainText('Campaign saved.');
  await selectFromRegistry(page, 'settlements', towns[0]!.name);
  await openSelectedOrders(page);
  const charter = page.getByTestId('settlement-charter');
  await charter.locator(':scope > summary').click();
  await charter.getByRole('combobox', { name: 'Focus', exact: true }).selectOption('learning');
  await charter.getByRole('button', { name: 'Update charter', exact: true }).click();
  await expect.poll(() => page.evaluate(() => window.__THEANDRIL__!.getSummary()!.charters.filter(item => item.focus === 'learning').length)).toBe(1);
  expect(await page.evaluate(() => window.__THEANDRIL__!.getSummary()!.charters.filter(item => item.focus === 'wealth').length)).toBe(39);
  await page.setViewportSize({ width: 390, height: 844 });
  await openRegistry(page, 'settlements');
  await search.fill('');
  await group.getByRole('button', { name: 'Select matching hearths', exact: true }).click();
  await group.getByLabel('Coin ceiling per hearth').fill('');
  await expect(group.getByRole('button', { name: 'Apply charters (40)', exact: true })).toBeDisabled();
  await group.scrollIntoViewIfNeeded();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('group-charters-narrow.png') });
  await group.getByRole('button', { name: 'Revoke charters (40)', exact: true }).click();
  await expect(page.getByTestId('group-charter-results')).toContainText('40 orders accepted · 0 refused');
  expect(await page.evaluate(() => window.__THEANDRIL__!.getSummary()!.charters.length)).toBe(0);
  expect(await page.evaluate(() => window.__THEANDRIL__!.getSummary()!.ownSettlements.map(town => town.queue))).toEqual(before.view.ownSettlements.map(town => town.queue));
  await closeManagement(page);
  await page.getByTestId('campaign-menu').locator(':scope > summary').click();
  await page.getByRole('button', { name: 'Load campaign', exact: true }).click();
  await expect(page.getByTestId('feedback')).toContainText('Campaign restored.');
  expect(await page.evaluate(() => window.__THEANDRIL__!.getStateHash())).toBe(after.hash);
  await openRegistry(page, 'settlements');
  await expect(group).toContainText('0 hearths selected');
  expect(errors).toEqual([]);
});

test('a partly refused group retains only the hearth whose new charter exceeded the canonical limit', async ({ page }) => {
  const game = empireLandCampaign('legendary');
  const towns = Object.values(game.settlements).sort((a, b) => a.id < b.id ? -1 : 1);
  towns.forEach((town, index) => { town.name = `Limit hearth ${String(index + 1).padStart(3, '0')}`; });
  // Authored legal save boundary: lost foreign hearth records await next-turn pruning.
  game.charters = [{ settlementId: towns[0]!.id, factionId: game.turnOwnerId, focus: 'works' as const, ceiling: 24 },
    ...Array.from({ length: 4095 }, (_, index) => ({ settlementId: `town.expired.${String(index).padStart(4, '0')}`, factionId: game.factions[1]!.id, focus: 'works' as const, ceiling: 24 }))]
    .sort((a, b) => a.settlementId < b.settlementId ? -1 : 1);
  await page.goto('/');
  await page.locator('input[type=file]').setInputFiles({ name: 'limited-group-charters.theandril', mimeType: 'application/gzip', buffer: Buffer.from(await exportSave(serializeGame(game))) });
  await expect(page.getByTestId('feedback')).toContainText('Imported campaign');
  await openRegistry(page, 'settlements');
  const registry = page.getByTestId('settlement-registry'), group = page.getByTestId('group-charters');
  await registry.getByRole('checkbox').nth(0).check();
  await registry.getByRole('checkbox').nth(1).check();
  await group.getByRole('button', { name: 'Apply charters (2)', exact: true }).click();
  await expect(page.getByTestId('group-charter-results')).toContainText('1 orders accepted · 1 refused');
  await expect(page.getByTestId('group-charter-results')).toContainText('as many charters as it may');
  await expect(group).toContainText('1 hearth selected');
  await expect(registry.getByRole('checkbox').nth(0)).not.toBeChecked();
  await expect(registry.getByRole('checkbox').nth(1)).toBeChecked();
  expect(await page.evaluate(() => window.__THEANDRIL__!.getSummary()!.charters.length)).toBe(1);
});
