import { Fragment, StrictMode, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { SiteShell } from './SiteShell';
import { evidenceUrl, localUrl } from './journal';
import type { Inline, LoreDocument } from '../../../../scripts/build-lore.ts';
import library from './lore/library.json';
import './journal.css';
import './lore.css';

type Document = LoreDocument; type Book = { id: string; title: string; documents: Document[] };
const books = library.books as unknown as Book[];
const base = import.meta.env.BASE_URL;
const loreUrl = (book?: string, chapter?: string) => `${localUrl(base, 'updates/lore/')}${book ? `?${new URLSearchParams(chapter ? { book, chapter } : { book })}` : ''}`;
const findBook = (id: string | null) => books.find(book => book.id === id);
const findDocument = (book: Book, chapter: string | null) => book.documents.find(document => document.id === chapter);
function Text({ nodes, sourcePath }: { nodes: readonly Inline[]; sourcePath?: string }) { return <>{nodes.map((node, index) => {
  const key = `${index}-${'value' in node ? node.value : node.label}`;
  if (node.type === 'strong') return <strong key={key}>{node.value}</strong>; if (node.type === 'em') return <em key={key}>{node.value}</em>; if (node.type === 'code') return <code key={key}>{node.value}</code>;
  if (node.type === 'wikilink') { const target = books.find(book => book.id === 'broken-roads')!.documents.find(document => document.title === node.target || document.id === node.target.toLocaleLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')); return target ? <a key={key} href={loreUrl('broken-roads', target.id)}>{node.label}</a> : <span key={key}>{node.label}</span>; }
  if (node.type === 'link') { const href = node.href.replace(/^<|>$/g, ''); const path = sourcePath && !href.startsWith('/') ? new URL(href, `https://source.invalid/${sourcePath}`).pathname.slice(1) : href; return <a key={key} href={href.startsWith('http') || href.startsWith('#') ? href : evidenceUrl(path)}>{node.label}</a>; }
  return <Fragment key={key}>{node.value}</Fragment>;
})}</> }
function Blocks({ document }: { document: Document }) { return <>{document.blocks.map((block, index) => {
  const key = `${block.type}-${index}`;
  if (block.type === 'heading') { const Tag = `h${Math.min(block.level + 1, 4)}` as 'h2' | 'h3' | 'h4'; return <Tag key={key} id={block.id}><Text nodes={block.children as Inline[]} sourcePath={document.sourcePath} /></Tag>; }
  if (block.type === 'paragraph') return <p key={key}><Text nodes={block.children as Inline[]} sourcePath={document.sourcePath} /></p>;
  if (block.type === 'blockquote') return <blockquote key={key}><Text nodes={block.children as Inline[]} sourcePath={document.sourcePath} /></blockquote>;
  if (block.type === 'callout') return <aside key={key} className="lore-callout"><strong>{block.title}</strong><p><Text nodes={block.children as Inline[]} sourcePath={document.sourcePath} /></p></aside>;
  if (block.type === 'list') { const Tag = block.ordered ? 'ol' : 'ul'; return <Tag key={key}>{block.items.map((item, itemIndex) => <li key={itemIndex}><Text nodes={item as Inline[]} sourcePath={document.sourcePath} /></li>)}</Tag>; }
  if (block.type === 'table') return <div className="lore-table-wrap"><table key={key}><thead><tr>{block.headers.map((cell, cellIndex) => <th key={cellIndex}><Text nodes={cell as Inline[]} sourcePath={document.sourcePath} /></th>)}</tr></thead><tbody>{block.rows.map((row, rowIndex) => <tr key={rowIndex}>{row.map((cell, cellIndex) => <td key={cellIndex}><Text nodes={cell as Inline[]} sourcePath={document.sourcePath} /></td>)}</tr>)}</tbody></table></div>;
  return null;
})}</> }
function Shelf() { const [query, setQuery] = useState(new URLSearchParams(window.location.search).get('q') ?? ''); const words = query.toLocaleLowerCase('en').trim().split(/\s+/).filter(Boolean); const docs = books.flatMap(book => book.documents.map(document => ({ book, document }))).filter(({ book, document }) => words.every(word => `${book.title} ${document.title} ${document.body}`.toLocaleLowerCase('en').includes(word)));
  const update = (value: string) => { setQuery(value); window.history.replaceState(null, '', `${loreUrl()}${value ? `?q=${encodeURIComponent(value)}` : ''}`); };
  return <><header className="masthead lore-masthead"><div><p className="eyebrow">Theandril library <span aria-hidden="true">/</span> source-bound reading</p><h1>The <em>lore</em> shelf</h1></div><p className="masthead-note">Four volumes kept in their original words. Follow the roads, then decide what remains unsettled.</p></header><section className="lore-search" aria-labelledby="lore-search-title"><label id="lore-search-title" htmlFor="lore-search">Search all lore</label><input id="lore-search" type="search" value={query} placeholder="A place, a question, a name…" onChange={event => update(event.target.value)} /><p role="status" aria-live="polite">{docs.length} {docs.length === 1 ? 'document' : 'documents'}</p></section><section className="lore-shelf" aria-label="Lore volumes">{books.map(book => <article key={book.id} className="lore-volume"><p className="eyebrow">{book.id === 'broken-roads' ? `${book.documents.length} chapters & appendix` : 'Reference volume'}</p><h2><a href={loreUrl(book.id, book.documents.length === 1 ? book.documents[0]!.id : undefined)}>{book.title}</a></h2><ol>{book.documents.filter(document => !words.length || docs.some(result => result.document === document)).map(document => <li key={document.id}><a href={loreUrl(book.id, document.id)}>{document.title}</a></li>)}</ol></article>)}</section>{!docs.length && <section className="no-results"><h2>No lore found</h2><p>Try another word. Search includes the complete text of every source volume.</p></section>}</> }
function Reader({ book, document }: { book: Book; document: Document }) { const index = book.documents.indexOf(document); const previous = book.documents[index - 1]; const next = book.documents[index + 1]; const headings = document.blocks.filter((block): block is Extract<typeof block, { type: 'heading' }> => block.type === 'heading'); useEffect(() => { document.title = `${document.title} · Theandril lore library`; }, [document]); return <article className="reader lore-reader"><a className="back-link" href={loreUrl()}><span aria-hidden="true">← </span>The lore shelf</a><header className="article-header"><p className="eyebrow">{book.title}</p><h1>{document.title}</h1><p className="byline">Read from the source record · <a href={evidenceUrl(document.sourcePath)}>View markdown ↗</a></p></header><div className="reading-layout"><aside className="article-index"><nav aria-label="In this volume"><p className="eyebrow">In this volume</p><ol>{headings.map(heading => <li key={heading.id}><a href={`#${heading.id}`}><Text nodes={heading.children as Inline[]} /></a></li>)}</ol></nav></aside><div className="article-body lore-body"><Blocks document={document} /><nav className="lore-pagination" aria-label="Continue reading">{previous && <a href={loreUrl(book.id, previous.id)}>← {previous.title}</a>}{next && <a href={loreUrl(book.id, next.id)}>{next.title} →</a>}</nav></div></div></article> }
function Lore() { const params = new URLSearchParams(window.location.search); const requestedBook = params.get('book'); const book = findBook(requestedBook); const requestedChapter = params.get('chapter'); const document = book && findDocument(book, requestedChapter); const missing = Boolean(requestedBook && (!book || !requestedChapter || !document)); return <SiteShell page="lore" base={base}>{missing ? <section className="missing-dispatch"><p className="eyebrow">Unlisted volume</p><h1>That page is not in the library</h1><p>This link may be incomplete or point outside the public source-bound collection.</p><a className="plaque" href={loreUrl()}>Browse the lore shelf →</a></section> : book && document ? <Reader book={book} document={document} /> : <Shelf />}</SiteShell> }
createRoot(document.getElementById('root')!).render(<StrictMode><Lore /></StrictMode>);
