import type { Dispatch } from './types';

/** Reviewed implementation evidence; this article has separate publication checks. */
export const productionSequencesRevision = '420219d278ae17f42a04871c6319ecf62a4af216';
export const productionSequencesVerification = 'The pinned implementation passes 1,975 headless tests across 247 files in 59.76 seconds. Thirty affected Chromium gameplay journeys pass in 3.9 minutes. One separate built-production sequence journey passes in 7.3 seconds, with an 8.3-second complete test run, through generated campaigns and ordinary controls without development hooks. Typecheck, lint, content/art validation and the Pages-subpath build pass. These overlapping scopes are reported separately, not added together; they precede this tenth article and its separate publication checks.';

export const productionSequencesDispatch: Dispatch = {
  publication: 'published', sourceRevision: productionSequencesRevision, sequence: 10,
  id: 'production-sequences', edition: '10', title: 'Queue a plan across your hearths',
  subtitle: '26 September 2026 · Production sequences',
  summary: 'Arrange a short production list, recall the hearths that need it and see which projects were paid for. Personal templates keep useful plans ready while every order still uses the existing queues.',
  topic: 'Engineering', tags: ['Empire management', 'Production', 'Templates', 'Browser storage', 'Performance'],
  status: 'Reviewed checkpoint', checkpoint: 'Production sequences · ACT-32', image: 'production-sequence-results',
  takeaways: [
    'Apply an ordered list of one to five projects to up to 128 selected hearths. Existing work stays first and accepted items spend ordinary coin immediately.',
    'Keep up to twenty-four named production templates in this browser. Choosing, recalling and applying are separate actions; campaign exports contain the paid queues, not the personal library.',
    'A refusal preserves the paid prefix and stops that hearth’s remaining list. Review partial results before another manual Apply. M3 and all fifteen release gates remain open.',
  ],
  sections: [
    { id: 'one-list-many-hearths', title: 'One list, many hearths', paragraphs: [
      'Several hearths may need the same practical start: recruit an Oath guard, build a Cinder workshop, then recruit another guard. Recall a saved hearth group or check the towns in the registry, arrange that list once and choose Apply production. The list holds one to five existing construction or recruitment items, with controls to move and remove each entry. Recruitment can repeat; a building appears only once in the editor’s list.',
      'The authored forty-hearth example uses Guard → Workshop → Guard: 120 ordinary queue orders costing 1,440 coin at the current prices. Its existing granary stays at the front of its hearth’s queue, and two Works charter policies remain intact. The realm has one hundred owned armies and 4,000 armies overall; that ownership is a controlled regression setup, not a claim that a player organically built the pictured empire.',
      'The compact illustration is the actual result summary after that explicit application: forty hearths complete, 120 orders accepted and no refusals. It is an exact 318-by-39-pixel native locator PNG, 4,767 bytes, captured inside a 390-pixel viewport with no later crop, resize or re-encoding. It shows only the result summary; the original full desktop and narrow captures retain the surrounding editor and registry. This is an authored Legendary, generator-4, seed-20260905 regression, not an organically grown realm.',
    ] },
    { id: 'spend-from-one-treasury', title: 'Spend from one treasury', paragraphs: [
      'All selected hearths draw from the same treasury. They run in stable hearth ID order, and each receives the items in the order you chose. The form shows the current treasury, nominal per-hearth and total cost, existing queue counts and canonical blockers for the currently chosen project. Nominal cost does not promise eligibility: a workshop just added to a queue has not finished and cannot unlock a later project immediately.',
      'If a building is already built or queued, a queue fills, a prerequisite is missing or funds run out, that hearth stops at the refused item. Its accepted prefix remains paid and queued. Processing continues with the next hearth. Complete hearths leave the checked selection; partial and refused hearths stay selected, with the attempted items, refusal and unattempted remainder available to review.',
      'There is no automatic retry or rollback. A second Apply submits the current whole list, so remove or change work already accepted before trying again. Otherwise an accepted unit can be recruited again. Existing single-hearth controls remain available for a different order, and the saved campaign retains these ordinary paid queues.',
    ] },
    { id: 'remember-the-plan-separately', title: 'Remember the plan separately', paragraphs: [
      'Save up to twenty-four production templates with unique names of up to forty characters. Each holds only its name and ordered list. Choosing a saved entry inspects it; Recall production template copies the list into the editable form. Apply production remains the separate action that issues orders. Save, Update, Recall and Delete never spend campaign resources or send a game command.',
      'The personal library belongs to this browser and origin. It survives refresh and a change of campaign, but is not included in campaign exports or synchronized to another device. It does not refresh live from another tab; competing writes serialize and edits to the same template use the last committed write. Campaign-owned selection groups remember which hearths to check, while personal production templates remember what list to consider. Applied queues and active charters remain canonical campaign state.',
      'Malformed, unsupported or inaccessible preference storage produces an explicit error without deleting rows or silently presenting an empty library. Direct sequence editing and Apply remain usable while a library operation waits or fails. Retry opens a fresh connection. A committed change followed by a failed refresh is reported as saved, with the refresh failure kept visible.',
    ] },
    { id: 'ordinary-orders-one-publication', title: 'Ordinary orders, one publication', paragraphs: [
      'The batch is a bounded convenience over existing queue commands. The worker validates the whole request before mutation, accepts up to 128 distinct hearth IDs and at most five items, sorts the hearths and records each attempted ordinary command. The simulation still decides ownership, affordability, prerequisites, duplicates and queue capacity. One final permitted observation carries the results, with at most 640 attempted commands.',
      'The main thread compares the reply with the submitted hearths and item order before announcing success. Missing, malformed or unexpected replies cannot become a successful result. Recording or publication interruption requires restoring a saved campaign. Independent review also found that a worker crash after paid work could leave order controls unlocked; the corrected path settles pending work and locks uncertain campaigns until restoration, while ignoring errors from replaced workers.',
      'The browser’s initial transfer assertion expected one worker request but saw two. Inspection identified the selected army’s existing movement-range refresh after the changed campaign hash. The corrected test requires exactly one production request/state and one correlated, target-free movement query with the same final hash. It retains the state-byte assertion and records movement reply bytes separately; it does not allow arbitrary extra orders or observations.',
    ] },
    { id: 'measure-the-payload', title: 'Measure the payload', paragraphs: [
      'A separate authored Small-map worker probe applies the same three-item list to forty hearths. Batched and serial execution produce the exact same archive and final hash, bbbaecff. The batch publishes one state containing 210,762 measured payload bytes, including 6,864 result bytes; the 120 serial states total 22,970,874 bytes. Saved continuation, existing queues and fog also match. This is a headless transport comparison, not a browser frame-time distribution.',
      'The generator-4 Legendary benchmark has 307,200 cells, forty realms and 4,000 armies. Its forty-hearth list publishes 4,399,407 bytes in a single 199.278-millisecond sample. The expanded 128-hearth, five-item ceiling publishes 4,842,958 bytes in 245.647 milliseconds, with 3.854 milliseconds reported for command work. Both carry a 39-byte empty cell-transfer header; the substantial observation payload remains a real cost.',
      'Huge and Legendary measurements are one elapsed sample per authored workload on the retained machine. Setup, import, export and replay are outside the timed batch. Each case verifies recorded order, exact replay and unchanged fog. These samples do not establish full-turn latency, rendering, retained memory, current-generator dimensions or organically grown mature-campaign performance.',
    ] },
    { id: 'verify-and-continue', title: 'Verify and continue', paragraphs: [
      productionSequencesVerification,
      'The affected journeys cover the ordered editor, repeated units, keyboard recall, 390-pixel controls, template CRUD and reload, export exclusion, shared-budget and queue refusals, ordinary individual additions and saved restoration. Separate cases expose denied, transient and malformed storage, and damaged worker replies or a worker crash after real paid work. Authored scale fixtures, generated production play and headless tests are overlapping execution scopes, reported separately rather than added together.',
      'Rules/save remain 32 and content remains 015468d1. No canonical rule, price, AI policy or campaign-resolution behavior changes, so no new pacing run is claimed. The dated rules31 headline remains Standard 234, Long 342 and Epic 379; Standard and Long still need work toward their approximate targets. A passing production workflow does not resolve those campaign limits.',
      'This advances existing ACT-32/M3 production-sequence scope and evidence for Gates I, E, D and K. No gameplay obligation is added or cut. M3 remains in progress: theater strategy, patrol and escort roles, reusable army order templates, broader governor decisions and combined mature-realm acceptance remain open. This slice adds no standing repeat cycle, queue refunds/reordering or per-hearth automatic resume. All fifteen release gates remain open.',
      'Contributors can extend the shared registry and ordinary command boundary, keeping accepted work visible and individual overrides available. Future delegation should be demonstrated through actual controls, saved continuation and representative mature campaigns, with bounded transfer measurements and independent review rather than another disconnected management screen.',
    ] },
  ],
  evidence: [
    { label: 'Production sequences verification', path: 'docs/development/2026-09-26-production-sequences/README.md', note: 'Exact execution scopes, retained failures, authored/generated boundaries, source reviews and remaining acceptance.' },
    { label: 'Production sequences architecture', path: 'docs/architecture/0043-production-sequences.md', note: 'Ordinary paid queues, stable bounded batches, partial prefixes and the separate personal library.' },
    { label: 'Independent UI review', path: 'docs/development/2026-09-26-production-sequences/ui-review.md', note: 'Preference/order separation, direct-control availability, session lifetime and manual partial-plan correction; authorship disclosed.' },
    { label: 'Independent storage and main-thread review', path: 'docs/development/2026-09-26-production-sequences/storage-main-review.md', note: 'Strict preference transactions, submitted-plan correlation and the corrected worker-crash recovery lock.' },
    { label: 'Authored browser workflow', path: 'tests/gameplay/production-sequences.spec.ts', note: 'Forty-hearth application, exact serial hash, separate read refresh, paid prefixes, library actions and saved continuation.' },
    { label: 'Generated production workflow', path: 'tests/production/production-sequences.spec.ts', note: 'Ordinary production controls, browser-local reuse and saved queues without development hooks; retained execution evidence is separate.' },
    { label: 'Actual worker serial comparison', path: 'docs/development/2026-09-26-production-sequences/worker-serial-probe.log', note: 'One versus 120 states in a separate authored Small-map fixture, exact archive/hash and measured payload bytes.' },
    { label: 'Huge and Legendary worker samples', path: 'docs/development/2026-09-26-production-sequences/worker-benchmark.jsonl', note: 'Single elapsed samples, 640-attempt ceiling, multi-megabyte payloads and explicit timing exclusions.' },
  ],
};
