import type { Dispatch } from './types';

export const reinforcementLogisticsRevision = 'f33a816f3a853229695b902af007e4e3f3547275';
export const reinforcementLogisticsVerification = 'The implementation passes 2,146 headless checks across 266 files and 49 affected Chromium journeys. Two separate built-production journeys pass without development hooks in 10.4 seconds. The focused historical scope passes 102 checks across seven files. These overlapping scopes are not additive. Typecheck, lint, content and art validation, and the Pages-subpath build pass; publication checks remain separately recorded in the work packet.';
export const reinforcementLogisticsDispatch: Dispatch = {
  publication: 'published', sourceRevision: reinforcementLogisticsRevision, sequence: 13,
  id: 'reinforcement-logistics', edition: '13', title: 'Hold the frontier, provision the crossing',
  subtitle: '28 September 2026 · Reinforcement and negotiated supply',
  summary: 'Let a standing watch respond to visible threats, and buy supplies from a foreign harbor. Joined empire controls keep shortages and blocked orders visible across a large realm.',
  topic: 'Engineering', tags: ['Empire management', 'Supply', 'Diplomacy', 'AI', 'Saved campaigns'],
  status: 'Reviewed checkpoint', checkpoint: 'Reinforcement and supply access · rules 34', image: 'fleet-provisions-refilled-narrow',
  takeaways: [
    'Opt a watch into up to four extra guards near a visible enemy, preserving physical garrisons and direct orders.',
    'Negotiate supply from one foreign hearth or harbor. Pay once on acceptance, inspect expiry and end service explicitly.',
    'An authored 128-army, thirty-hearth journey joins delegation, shared budgets, blocked travel and saved continuation. M3, M4 and all fifteen release gates remain open.',
  ],
  sections: [
    { id: 'respond-to-a-visible-threat', title: 'Respond to a visible threat', paragraphs: [
      'A watch can now send an idle reserve toward an approaching enemy even when its ordinary garrison is staffed. Choose zero to four extra guards in the defensive-theater controls. Each visible wartime combat land army within three hexes requests one extra guard up to that limit. Hidden armies, neutral forces, caravans and embarked passengers do not trigger it. These are army-container counts, not estimates of opposing combat strength.',
      'Extra coverage remains through one quiet allocation before surplus can return. Physical guard floors and direct active or paused routes, postings, missions, sieges and voyages retain priority. Incoming promises never license withdrawing a physical guard. Each theater still attempts at most sixteen ordinary routes per turn; blocked assignments remain in its actual report. Existing watches migrate with reinforcement off. New AI watches may choose one extra guard and up to three spare members while retaining scouts and their two strongest field armies; existing watches are not rewritten or refilled.',
    ] },
    { id: 'work-through-the-exceptions', title: 'Work through the exceptions', paragraphs: [
      'Delegated idle armies leave the ordinary movement queue. A grouped theater warning instead opens the affected watch, where missing guards, unavailable hearths and actual refused dispatches can be inspected. Paused direct routes and stalled postings remain actionable. Keyboard navigation now defers focus until the registry window has opened, correcting a race found by the integrated browser journey.',
      'The acceptance exercise combines 128 owned armies and thirty hearths on a Huge world: saved groups, policies, a personal production template, a finite shared purse, paid prefixes and refusals, reviewed group travel, a stranded member, reinforcement and individual detachment. Actual UI End turns, manual restoration and portable import reproduce the same AI-inclusive future and replay. Ownership, infrastructure and a local frontier patch are explicitly authored; disclosed threat placement isolates the workflow from an unrelated tactical battle. The shared purse falls from 44 to 8 coin after explicit production, then to zero through ordinary upkeep. Twenty-eight empty charters correctly wait at their reserve while paid granary work advances. This is not an organically earned mature empire or a complete governor.',
    ] },
    { id: 'buy-a-supply-line', title: 'Buy access to a supply line', paragraphs: [
      'Choose a currently observed foreign hearth or harbor in diplomacy, review a fee and a five-to-thirty-turn term, then send the request. The public quote is two coin per turn: twenty coin for ten turns. The request lasts three turns and payment happens once when the provider accepts. Either participant can end service without a refund. War, lost ownership and expiry end the agreement; ordinary sieges and supply blockers can interrupt feeding.',
      'In the authored overseas journey, the provider AI accepts a twenty-coin request on End turn. Reedwatch Quay feeds a field force and refills the depleted loaded fleet to eight provision turns. On the next turn after access ends, stores fall to seven turns aboard ship and each unsupported land formation loses four strength. Renegotiation replenishes the fleet and stops further land losses. A separate provider-seat journey accepts through human controls and verifies exactly one payment. Saves, portable data and command replay retain the agreement.',
      'The illustration is the earlier 23 September harbor-replenishment capture: Lantern ferry has eight provision turns at Charter Quay. It shows the existing supply display, not the new negotiation. The new native agreement and narrow request captures are linked as source evidence below. Reusing the unchanged reviewed image adds no public image bytes.',
      'The agreement buys supply from one named source. It grants no passage, alliance or shared intelligence. The map uses disclosed last-known contracted reach; own forces report whether they are actually fed. Bounded AI purchases consider at most two needy actors, four observed sources and eight ordinary movement previews, keep existing routes, and reserve promised fees before discretionary paid peace. A nearer known supply line vetoes a purchase conservatively.',
    ] },
    { id: 'preserve-and-measure', title: 'Preserve the campaign and measure the cost', paragraphs: [
      'Rules/save 34 keeps content 015468d1 unchanged. Ten genuine pre-change rules 33 checkpoints preserve original save/archive bytes, 27 repeated accepted commands and seven continuation seals. Mixed history, strict future-field rejection, paid agreements and reopened storage are verified. Review reproduced an AI-payment recovery defect inside End turn and AI watch: payment and autosave succeeded, but a failed view could leave stale controls active. The corrected request-wide guard requires restoration and never pays twice; both original regressions pass unchanged.',
      'One warmup and three identical-save samples put isolated reinforcement allocation at 1.600/2.338 ms for the Huge/Legendary representative cases and 9.259/9.466 ms at the single-realm ceilings. Eight paid imports take 0.837/0.605 ms for actual supply graphs; full own observations take 12.196/26.999 ms, compared with 9.829/27.222 ms without agreements. The small negative difference is sample variability, not a speedup. Useful-source AI planning takes 0.208/0.200 ms. Setup, loading and replay are outside timing; no frame-time or all-realm saturation claim follows. The integrated browser run observes 21,670,006 bytes across twelve state publications: these are aggregate correctness-run transfers, not a quiet performance sample.',
      reinforcementLogisticsVerification,
      'Three predetermined seeds on Standard maps with twelve realms finish at Standard 233/211/225, Long 311/312/309 and Epic 349/367/373 under both frozen rules 33 and current rules 34. Old hashes and command/event counts match the genuine pre-change baseline. DH-021 remains open: Standard and Long exceed approximate 200/300 targets, and one Epic seed is a turn below 350. No price or tiny proxy bound changed. These headline campaigns make no supply requests. Five accepted ordinary routes target hearths carrying reinforcement holds across nine current campaigns; identical command/event counts across versions mean that association does not prove reinforcement caused extra dispatches. Authored planner, worker and browser cases exercise the additions directly. Unchanged pacing is not proof of organic adoption.',
      'Initial measurement results are retained as invalid paired-history evidence: the tool selected historical creation but then ran current rules. The corrected tool scopes observations, AI, commands and final hashes together. Initial browser, sandbox and test-concurrency failures are also retained beside their corrected results.',
    ] },
    { id: 'toward-one-point-zero', title: 'The work still ahead', paragraphs: [
      'This advances existing ACT-32/M3 delegation, ACT-33/M4 logistics and ACT-38/DH-021 measurement. No gameplay obligation was added or removed. Patrols, escorts, reusable army orders, broader governors, recurring trade, wider diplomatic obligations and sustained coordinated overseas wars remain unfinished. All fifteen release gates remain open. Deployment is a development checkpoint, not 1.0 acceptance.',
    ] },
  ],
  evidence: [
    { label: 'Implementation and retained failures', path: 'docs/development/2026-09-27-reinforcement-logistics/README.md', note: 'Exact verification scopes, authored versus organic evidence and remaining limits.' },
    { label: 'Canonical reinforcement and supply architecture', path: 'docs/architecture/0046-reinforcement-supply-access.md', note: 'Bounds, payment lifecycle, actual supply, permitted forecasts and historical migration.' },
    { label: 'Integrated mature-realm acceptance', path: 'docs/development/2026-09-27-reinforcement-logistics/integrated-acceptance.md', note: 'Joined budgets, policies, travel, watch exceptions, overrides and exact saved futures; authored setup disclosed.' },
    { label: 'New harbor agreement capture', path: 'docs/development/2026-09-27-reinforcement-logistics/browser-evidence/supply-role-fixed/supply-access-negotiate-fo-47f93-over-with-a-saved-agreement/contracted-harbor-desktop.png', note: 'Real rules 34 UI in an authored naval journey; twenty coin, expiry and explicit no-refund termination.' },
    { label: 'Native supply image and UI review', path: 'docs/development/2026-09-27-reinforcement-logistics/supply-ui-review.md', note: 'Desktop and 390px controls, exact screenshot hashes and capture limitations.' },
    { label: 'AI-payment recovery review', path: 'docs/development/2026-09-27-reinforcement-logistics/worker-recovery-review.md', note: 'Two reproduced defects, unchanged passing regressions and exact restored payment.' },
    { label: 'Paired three-seed pacing', path: 'docs/development/2026-09-27-reinforcement-logistics/pacing-comparison.json', note: 'Nine unique headline combinations per rules version, baseline seals, real adoption counters and open DH-021.' },
    { label: 'Reinforcement measurements', path: 'docs/development/2026-09-27-reinforcement-logistics/reinforcement-benchmark-final.json', note: 'One warmup and three identical-save samples on four authored Huge/Legendary workloads.' },
    { label: 'Contract supply and AI measurements', path: 'docs/development/2026-09-27-reinforcement-logistics/supply-benchmark-final.json', note: 'Actual propagation, observed forecast, whole observation, lifecycle and bounded purchase planning with separate timing scopes.' },
  ],
};
